# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs

baseurl: /cru-web-styleguide

sass:
  sass_dir: ../
  style: expanded

github:
  repo: https://github.com/CruGlobal/cru-web-styleguide.git
